### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by alenweiru** [KeyForce/Cascade-RCNN-Tracking#1]
Can you provide the end to end model performance such as FPS?

**Comment by KeyForce** [comment]
This model's inferences time is very slow. FPS might between 0.5 and 3 under one single 1080Ti platform, if choosing ResNeXt101 as backbone.

But there are many ways to improve the speed of this demo, such as YOLO V4 Tricks.

[YOLOv4 | Medium](https://medium.com/@jonathan_hui/yolov4-c9901eaa8e61)

**Comment by alenweiru** [comment]
Thank you for your answer.It help me a lot.
