### ISSUE TITLE
关系MGN相似度度量问题

### ISSUE THREAD

**Issue by Fanghc95** [KeyForce/Cascade-RCNN-Tracking#11]
作者您好，在使用MGN提取行人特征时，我的场景下，提取的2048d的行人特征区分度很小，例如不同id，计算2048维的cosine距离差距只有0.01左右（范围0~1.0），虽然排序下来，同id会排在前面，但区分度很差。请问这样问题是否有解决方法。

P.S : 我的场景主要是跨镜匹配，并非用于mot，但使用了该项目同样的MGN特征提取网络

**Comment by KeyForce** [comment]
是用Triplet loss训练的吗？

**Comment by Fanghc95** [comment]
> 是用Triplet loss训练的吗？

是的，交叉熵和triplet一起。是不是和特征距离计算方法有关

**Comment by KeyForce** [comment]
我对ReID相关接触很少，不是特别清楚问题出在哪里，所以提供一下几个猜想
* 有没有训练好？模型收敛了吗？
* 先尝试用欧式距离或者马氏距离计算，看看训练效果正不正常
* 同ID的应该距离会大于0.5吧
* 对相似度对特征进行聚类看看效果如何

**Comment by Fanghc95** [comment]
> 我对ReID相关接触很少，不是特别清楚问题出在哪里，所以提供一下几个猜想
> 
> * 有没有训练好？模型收敛了吗？
> * 先尝试用欧式距离或者马氏距离计算，看看训练效果正不正常
> * 同ID的应该距离会大于0.5吧
> * 对相似度对特征进行聚类看看效果如何

好的，感谢！
