### ISSUE TITLE
FairMOT used DeepSort

### ISSUE THREAD

**Issue by wdkwyf** [KeyForce/Cascade-RCNN-Tracking#15]
Hi, I read FairMOT tracker [codes](https://github.com/ifzhang/FairMOT/blob/ca63d27f19e8d2170b84edb80cc2dc348c3dcd5a/src/lib/tracker/multitracker.py#L245), it's more like deepsort rather than MOTDT you mentioned in readme.

> 对于跟踪模块，目前来说还有更好的解决方案，比如使用MOTDT，此算法在DeepSort的基础上加入了轨迹评分的机制，目前像FairMOT、JDE使用的跟踪模块都是MOTDT，从精度和速度上此算法表现都是不错的。

Please correct me if I'm wrong. Thank you very much.

**Comment by KeyForce** [comment]
Hi

我看FairMOT的跟踪的代码实现跟MOTDT代码及其相似，基类的实现也是一样的

可以对比一下[Cascade-RCNN-Tracking/MOTDT/tracker/](https://github.com/KeyForce/Cascade-RCNN-Tracking/tree/master/MOTDT/tracker)和[FairMOT/src/lib/tracker/](https://github.com/ifzhang/FairMOT/tree/ca63d27f19e8d2170b84edb80cc2dc348c3dcd5a/src/lib/tracker)文件夹下三个文件的相似程度哈

我觉得在coding style上完全与MOTDT一致的，在跟踪细节的代码很大一部分也是MOTDT的代码，只是MOTDT没有在update中去推理过BBOX的框，这个其实在MOTDT里面直接当做输入参数了，FairMOT在这里是修改了一些注释，但是代码大部分是一致的[FairMOT/src/lib/tracker/multitracker.py](https://github.com/ifzhang/FairMOT/blob/ca63d27f19e8d2170b84edb80cc2dc348c3dcd5a/src/lib/tracker/multitracker.py#L245)
[Cascade-RCNN-Tracking/mot_tracker.py](https://github.com/KeyForce/Cascade-RCNN-Tracking/blob/master/MOTDT/tracker/mot_tracker.py#L204)
