### ISSUE TITLE
how can i get the model of 'model.pt' in the my_deep_sort_mgn.py?

### ISSUE THREAD

**Issue by ainilian** [KeyForce/Cascade-RCNN-Tracking#2]
"deepsort = build_tracker('/root/PycharmProjects/mmdet/mgn_sort/deep/checkpoint/model.pt', use_cuda=True)"  
the codes are in the my_deep_sort_mgn.py . i want to get the 'model.pt' to run the project.

**Comment by KeyForce** [comment]
Pretrained weight download from [Google Drive](https://drive.google.com/open?id=16V7ZsflBbINHPjh_UVYGBVO6NuSxEMTi) or [Baidu Drive](https://pan.baidu.com/s/12AkumLX10hLx9vh_SQwdyw) Password:mrl5

**Comment by ainilian** [comment]
thank you very much.
