### ISSUE TITLE
关于视频中某帧检测框为空的情况，那卡尔曼还能继续预测并被匹配更新吗？请问有没有考虑到这一点。

### ISSUE THREAD

**Issue by ainilian** [KeyForce/Cascade-RCNN-Tracking#3]
my_deep_sort_mgn.py这个文件中，第190行，如果检测模型没检测到目标框，即bbox_result为空，有没有可能出现这种情况，出现了咋整？

**Comment by KeyForce** [comment]
有可能出现这种情况的，若bbox_result为空，后面程序中[my_deep_sort_mgn.py Line73](https://github.com/KeyForce/Cascade-RCNN-Tracking/blob/master/my_deep_sort_mgn.py#L73)会引发assert断言。

这个算是一个Bug，建议在[my_deep_sort_mgn.py Line190](https://github.com/KeyForce/Cascade-RCNN-Tracking/blob/master/my_deep_sort_mgn.py#L190)加上
```python
if not bbox_result: 
    image_id += 1
    continue
```


对于跟踪算法，若出现丢失帧，且帧数小于n_init，是可以继续追踪的，如果大于这个值就失去目标了。

**Comment by ainilian** [comment]
明白了，谢谢！
