### ISSUE TITLE
Trackor

### ISSUE THREAD

**Issue by Leo63963** [KeyForce/Cascade-RCNN-Tracking#7]
请问你这里把Trackor改为只用私有的检测，而不用公共的检测是吗？原来代码里的predict_boxes这个函数已经没有了好像，谢谢．

**Comment by KeyForce** [comment]
是的，改成只用私有检测。
目前版本的Trackor是有Bug的。建议自己重新修改一下，这个还挺难改的，需要对Trackor代码很熟悉，不过我尝试过可以跑出正确结果。

**Comment by Leo63963** [comment]
你好，我现在似乎已经跑通了my_trackor的代码，也得到了一些结果。感谢分享。
请问，你跑的结果，和Tracktor那个paper里比起来，有没有提升？按道理用了更好的检测器后，MOTA会有提升。我这里跑的时候，我发现ID很乱。请问你有没有这个现象？谢谢。

**Comment by KeyForce** [comment]
ID变乱这个Bug我也遇到了，目前这个分支的Trackor修改得有问题。

我这边有重新修改的一份，可以跑出正确的结果，需要的话可以发给你参考一下。

我当初测试了Trackor感觉效果并没有提升很大，Trackor有个缺点是如果提高迭代次数，跟踪速度会变得特别慢。

**Comment by Leo63963** [comment]
感谢回复，如果可以的话，确实需要，感激不仅！
我的邮箱：leon63963@163.com
感谢！

**Comment by KeyForce** [comment]
原始版本的Trackor会加载跟踪区域重新进行检测，这份代码去除了这点，代码已经能通过直接加载BBox坐标进行跟踪（全新的数据集，没有GT标签，只有目标检测的结果），不过还需要再做一下代码移植，我觉得应该问题不大。

链接：https://pan.baidu.com/s/1SaPIEpE8vEqlp2Zr7LICHw 
提取码：1234

**Comment by Leo63963** [comment]
好的，感谢分享．
