### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Leo63963** [KeyForce/Cascade-RCNN-Tracking#8]
安装环境的过程中发现以下问题：
ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_0
我的环境是Ubuntu16.04，请问怎么解决？谢谢！

**Comment by KeyForce** [comment]
这应该是环境导致的原因。
建议先安装一下MMdetection（需要重新在当前环境编译），其他依赖库可以查看environment.yml进行手动安装（注意一下版本）。

**Comment by Leo63963** [comment]
非常感谢回复。还有个问题，我这里已经安装了mmdetection并且可以跑通，在mmdetection的环境下也安装了Trackor依赖的库，也可以跑通，但是直接在这个环境下跑my_trackor.py跑不通，显示的是：
Traceback (most recent call last):
  File "my_trackor.py", line 8, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result
  File "/home/lee/Detection/RCNN-Tracking-master/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version
我感觉跑my_trackor需要的包我应该都有。请问这个可能是什么问题？感谢。

**Comment by KeyForce** [comment]
这个是MMdetection没安装好

**Comment by Leo63963** [comment]
感谢回复，安装问题已解决．
